<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PhotoLibrarian.ML</RootNamespace>
    <Platforms>x64;ARM64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhotoLibrarian.Core\PhotoLibrarian.Core.csproj" />
    <ProjectReference Include="..\PhotoLibrarian.Inference\PhotoLibrarian.Inference.csproj" />
    <EmbeddedResource Include="Assets\tinyclip-calibration-general-v2-coverage.json" />
    <EmbeddedResource Include="Assets\auto-tag-hierarchy-v3.json" />
    <EmbeddedResource Include="Assets\general-photo-profile-v2.json" />
  </ItemGroup>
</Project>
