<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PhotoLibrarian.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MetadataExtractor" />
    <PackageReference Include="XmpCore" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
</Project>
